version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    image: roman23323/kittygram_backend:latest
    env_file: .env
    volumes:
      - media:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0:8000"
  frontend:
    env_file: .env
    image: roman23323/kittygram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: roman23323/kittygram_gateway:latest
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
